### ISSUE TITLE
My comments

### ISSUE THREAD

**Issue by tomerarazy** [sheinbergon/corrosion#2]
1st - This is a really nice job, overall the code is really clean and readable and the API is very clear and simple.

My main comment is naming - "Corroded" & "Corrosion" have no meaning to me in regard to threads. each time I encounter any of those terms I need to do a "mental translation" in my head which makes this much more difficult to understand.
I would much prefer to use standard terms: maybe "Pinned" instead of "Corroded" and "Pinning" instead of "Corrosion".

**Comment by sheinbergon** [comment]
Yep. It kind of bothered me as well. I like your suggestions, and I think I'm gonna apply them, and also rename this library

10x
